name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Prepare output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.YJC_AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: yjc2021
          destination-repository-name: FitLink-FE
          user-email: ${{ secrets.YJC_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: dev

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
